### ISSUE TITLE
Quick Note

### ISSUE THREAD

**Issue by zromick** [ConnerConnerConner/PyTime#1]
Heya! Just wanted to note that the original idea for this app (and a lot of design support for SPRT) came from me: https://discord.com/channels/352272170283696131/352272170711384064/527526867616399375

I like getting credit lol :))

**Comment by ConnerConnerConner** [comment]
I'd like to thank you for coming up with the original idea, would you mind if I added you to the readme?

**Comment by zromick** [comment]
Would love that :))
Also your remake of it has been added to the Mobile Speedrunning Discord's #start-here resource list!

**Comment by ConnerConnerConner** [comment]
alright I added you!
